ONSdigital/eq-schema-validator

Dockerfile, Pipfile, Pipfile.lock, ci/concourse.yml, requirements.txt, scripts/run_app.sh, test_requirements.txt
Change to using Pipenv for dependencies and virtual environment management.
Setup: `pip install -U pip pipenv`
Run: `pipenv run scripts/run_app.sh`
Fixes: #2
=> Replace requirements.txt with Pipfile and lock for use with Pipenv

schemas/common_definitions.json
Added the conditions to the schema to support routing on a number
=> Added number routing conditions

schemas/blocks/interstitial.json, schemas/blocks/questionnaire.json, schemas/common_definitions.json, tests/schemas/test_invalid_routing_block.json
updated Id to block in the schema and added additional properties
=> Rename id to block in goto routing rules

schemas/blocks/question.json, schemas/questionnaire_v1.json, tests/schemas/test_invalid_routing_block.json, tests/schemas/test_invalid_routing_group.json, tests/schemas/test_schema_id_regex.json
Changing of Questionnaire to Question now in blocks that is happening on runner. The schema validator will need to be updated to match this change as well.
Check all instances of Questionnaire have been changed and everything still functions i.e. tests etc.
Review also this PR: https://github.com/ONSdigital/eq-survey-runner/pull/1423
=> Rename block type from Questionnaire to Question

app/validation/validator.py, tests/schemas/test_invalid_numeric_answers.json, tests/test_schema_validation.py
Refactor of range type validation in validator. 
Added validation to make sure possible ranges in answer cannot be zero or lower.
To test alter a schema to fail range validation and run against schema-validator
=> Range validation refactor

schemas/blocks/section_summary.json, schemas/questionnaire_v1.json
Added validation around the section summary blocks
Card: https://trello.com/c/AC1836ru/1800-section-summary-m
Run Locally or in Docker against Runner to check if schema passes etc. the usual
=> Add Section Summary to Validator

app/validation/validator.py, schemas/questionnaire_v1.json, scripts/run_tests_unit.sh, tests/schemas/test_invalid_numeric_answers.json, tests/schemas/test_invalid_routing_block.json, tests/schemas/test_invalid_routing_group.json, tests/schemas/test_schema_id_regex.json, tests/test_schema_id_regex.py
See https://github.com/ONSdigital/eq-survey-runner/pull/1473
This alters the validator with the updated schema.
=> Promote section in schema

schemas/questionnaire_v1.json
Adding section summary to block
(Forgot to add this hence why build was failing oops)
PR based on: https://github.com/ONSdigital/eq-survey-runner/pull/1475
Run against `test_section_summary.json` locally to check it it validates etc.
=> Add section summary to block

app/validation/validator.py, schemas/blocks/question.json, schemas/questions/calculated.json, tests/schemas/test_invalid_id_in_grouped_answers_to_calculate.json, tests/test_schema_validation.py
Added new question type schema `Calculated`. 
Test against https://github.com/ONSdigital/eq-survey-runner/pull/1485
=> Eq 1868 validate sum against total

app/validation/validator.py, schemas/questions/calculated.json, tests/schemas/test_invalid_id_in_grouped_answers_to_calculate.json, tests/test_schema_validation.py
Just a quick PR to change `answers_to_group` name to `answers_to_calculate`
=> change list name from answers_to_group to answers_to_calculate

app/validation/validator.py, tests/schemas/test_invalid_numeric_answers.json, tests/schemas/test_numeric_default_with_routing.json, tests/test_schema_validation.py
This gets us around the issue where a defaulted value routes around a breakdown
=> Don't validate range for defaulted numeric

schemas/questions/calculated.json, schemas/questions/date_range.json, schemas/questions/general.json, schemas/questions/relationship.json, schemas/questions/repeating_answer.json
In relation to and needed to pass PR: https://github.com/ONSdigital/eq-survey-runner/pull/1540
Trello: https://trello.com/c/7Pqn9TmB/1936-remove-html-within-schemas-xs
Run locally against the related branch to check if it passes validator
=> Allow content to be defined at question level

app/validation/validator.py, schemas/answers/checkbox.json, schemas/answers/currency.json, schemas/answers/date.json, schemas/answers/definitions.json, schemas/answers/dropdown.json, schemas/answers/month_year_date.json, schemas/answers/number.json, schemas/answers/percentage.json, schemas/answers/radio.json, schemas/answers/relationship.json, schemas/answers/text_area.json, schemas/answers/text_field.json, schemas/answers/unit.json
Answer alias is removed from runner in ONSdigital/eq-survey-runner#1533
Do not merge until runner PR is merged.
=> Remove answer alias from schema

schemas/answers/checkbox.json
Format same as standard checkbox.
=> Add MutuallyExclusiveCheckbox answer type

schemas/questionnaire_v1.json, scripts/run_tests_unit.sh, tests/schemas/test_invalid_survey_id_whitespace.json, tests/test_schema_validation.py
Add validation rule for white space in survey id. Also added a unti test and updated the run_test.sh to use pipenv to run pytest.
=> Add validation for white space in survey id

schemas/common_definitions.json, schemas/questions/calculated.json, schemas/questions/date_range.json, schemas/questions/general.json, schemas/questions/relationship.json, schemas/questions/repeating_answer.json
Added question definition to validator.
Needed for: https://github.com/ONSdigital/eq-survey-runner/pull/1649
=> Added question definitions to JSON schema

app/validation/validator.py, schemas/blocks/confirmation.json, schemas/blocks/interstitial.json, schemas/blocks/question.json, schemas/questionnaire_v1.json, schemas/questions/calculated.json, schemas/questions/content.json, schemas/questions/general.json, schemas/questions/repeating_answer.json, tests/schemas/test_invalid_metadata.json
Require schemas to provide at least 1 entry for each defined array
=> Add minItems to be at least 1 to arrays

app/validation/validator.py, schemas/blocks/calculated_summary.json, schemas/questionnaire_v1.json, tests/schemas/test_invalid_calculated_summary.json, tests/test_schema_validation.py
Json schema checks
Answers used in calculation must be of same type (answer type, unit, currency)
=> Add CalculatedSummary block type

app/validation/validator.py, schemas/common_definitions.json, tests/schemas/test_invalid_routing_group.json, tests/test_schema_validation.py
=> Add a repeat type of 'group'

schemas/common_definitions.json
Modified definitions structure to allow `content` so we can display bullet points etc. Needed for: https://trello.com/c/rC82gUmp/2180-move-significant-changes-to-use-definition-pattern
Run against runner branch: https://github.com/ONSdigital/eq-survey-runner/pull/1712
Related PRs:
1. https://github.com/ONSdigital/eq-survey-runner/pull/1712
2. https://github.com/ONSdigital/eq-translations/pull/20
=> Update definition requirements

schemas/questionnaire_v1.json
- to only a-z, A-Z, hyphens and underscores
=> Restrict Metadata name

schemas/blocks/summary.json
Added collapsible key for summary
[Link to pr adding accordion to summary](https://github.com/ONSdigital/eq-survey-runner/pull/1720)
=> Add collapsible key for summary

app/validation/validator.py, tests/schemas/test_invalid_metadata.json
Existing test checks that this works.
https://github.com/ONSdigital/eq-survey-runner/pull/1732
=> Don't match collection_metadata in validation

schemas/questionnaire_v1.json
- Changed legal basis to be non mandatory and a string
- https://github.com/ONSdigital/eq-survey-runner/pull/1748
=> Update legal basis

schemas/blocks/answer_summary.json
Required for https://github.com/ONSdigital/eq-survey-runner/pull/1793
=> Make title and label required for AnswerSummary

app/validation/validator.py, schemas/common_definitions.json, tests/schemas/test_invalid_routing_when_answer_count.json, tests/test_schema_validation.py
https://trello.com/c/sBtFoRAQ/2482-add-routing-on-the-count-of-multiple-answers-to-when-rule-s
=> Update validator to handle new answer_count routing

schemas/common_definitions.json
###What is the context of this PR?
Author needs to be able to support writing inclusive comparators as part of the routing based on a number type answer. This PR allows those comparators to get though validator.
###How to review
Tests pass and routing is now possible using inclusive comparator signs.
=> Implemented greater/less than or equal too as a single condition

app/validation/validator.py
https://trello.com/c/3CGwoO1R/2514-remove-ignore-pylint-comments-in-eq-schema-validator
Quick refactor to remove pylint error.
Also added a few more docstrings that pylint was complaining about.  Nothing too informational but it gives hints as to what it returns which can be useful.
=> Refactor code to remove ignore pylint error comment

app/validation/validator.py, tests/schemas/test_invalid_routing_when_answer_count.json, tests/test_schema_validation.py
Ensure we always have a default routing rule.
This requires some changes to the schemas in runner to ensure everything validates.
https://github.com/ONSdigital/eq-survey-runner/pull/1863
=> Validate default routing rules

app/validation/validator.py, tests/schemas/test_decimal_places_must_be_defined_when_using_totaliser.json, tests/test_schema_validation.py
To enforce:
https://github.com/ONSdigital/eq-survey-runner/pull/1908
=> Ensure totaliser defines decimal places

Dockerfile
🤷‍♂️ 
This makes the docker container 52MB down from 377MB
=> Use alpine docker base image

schemas/string_interpolation/definitions.json, schemas/string_interpolation/transforms/first_non_empty_item.json, schemas/string_interpolation/transforms/remove_empty.json
This PR adds a couple of new transforms required by https://github.com/ONSdigital/eq-survey-runner/pull/2019
=> Additional transforms

schemas/common_definitions.json, schemas/string_interpolation/transforms/format_date.json
I have added 2 changes that are required to migrate all of the existing piping to placeholders
Add an additional date format
Allow Placeholders in content
=> Add additional date format and allow Placeholders in content

app/validation/validator.py, schemas/common_definitions.json, schemas/string_interpolation/definitions.json, schemas/string_interpolation/transforms/calculate_years_difference.json, schemas/string_interpolation/transforms/format_date.json, schemas/variants/content_variant.json, schemas/variants/question_variant.json, schemas/when_rule/compare_to_answer_store.json, schemas/when_rule/compare_to_list.json, schemas/when_rule/compare_to_value.json, schemas/when_rule/definitions.json, tests/schemas/invalid/test_invalid_answer_comparison_types.json, tests/schemas/invalid/test_invalid_when_condition_property.json, tests/schemas/valid/test_when_condition_property.json, tests/test_schema_validation.py
Ability to define a list of values in when condition.
Introduced these new conditions:
1. `equals any`
2. `not equals any`
3. `contains any`
4. `contains all`
Needed for https://github.com/ONSdigital/eq-survey-runner/pull/2041
=> Ability to define multiple values in when condition

.gitignore, app/validation/validator.py, schemas/common_definitions.json, schemas/when_rule/compare_to_list_count.json, schemas/when_rule/compare_to_multiple_values.json, schemas/when_rule/definitions.json, tests/schemas/invalid/test_invalid_answer_comparison_types.json, tests/schemas/invalid/test_invalid_when_condition_list_property.json, tests/test_schema_validation.py
Adds lists to when rules to enable routing logic based on the number of items in a list.
=> Add lists to when rules

app/validation/validator.py, tests/schemas/invalid/test_invalid_inconsistent_default_answers_in_variants.json, tests/schemas/invalid/test_invalid_placeholder_question_not_mandatory.json, tests/test_schema_validation.py
Amended the '_ensure_relevant_variant_fields_are_consistent' validation method to include a check that asserts that default values are the same across question variants.
=> Added a check for default values in question variants

schemas/blocks/list_collector.json, tests/schemas/valid/test_list_collector.json
Adds a `summary` definition in the list collector json.
=> Add list collector summary definition to schema

app/validation/validator.py, schemas/questionnaire_v1.json, tests/schemas/invalid/test_invalid_hub_section_definition.json, tests/schemas/valid/test_hub_and_spoke.json, tests/schemas/valid/test_hub_section_ids.json, tests/test_schema_validation.py
The hub should be inaccessible until certain sections are complete.
Add a key to the hub definition to support the definition of sections which should be completed before the hub is accessible.
=> Add required sections

app/validation/validator.py, schemas/questionnaire_v1.json, tests/schemas/invalid/test_invalid_repeating_section_list_name.json, tests/schemas/valid/test_repeating_section.json, tests/test_schema_validation.py
Validate that the schema for https://github.com/ONSdigital/eq-survey-runner/pull/2248
I have decided not to validate that referenced answer ids do not exist within a repeat at the moment.
=> Validate repeating sections

app/validation/validator.py, schemas/answer_actions/redirect_to_list_add_question.json, schemas/answers/definitions.json, tests/schemas/invalid/test_invalid_answer_action_redirect_to_list_add_question.json, tests/schemas/valid/test_answer_action_redirect_to_list_add_question.json, tests/test_schema_validation.py
Added support for answer actions feature introduced in https://github.com/ONSdigital/eq-survey-runner/pull/2301
Test with https://github.com/ONSdigital/eq-survey-runner/pull/2301
=> Add support for answer action

schemas/questions/types/general.json, schemas/questions/types/mutually_exclusive.json
This adds new instruction pattern rule to questions. Requested changes are listed on [Trello card](https://trello.com/c/t67BKLuo/3448-update-ccs-with-new-instruction-pattern).
=> Add rules for ccs instruction pattern

Dockerfile, Pipfile, Pipfile.lock, app/validation/validator.py, schemas/answers/definitions.json, tests/schemas/invalid/test_invalid_list_collector_driving_question_multiple_collectors.json, tests/schemas/invalid/test_invalid_list_collector_driving_question_multiple_driving_questions.json, tests/schemas/invalid/test_invalid_quotes_in_schema_text.json, tests/schemas/invalid/test_invalid_repeating_section_list_name.json, tests/schemas/invalid/test_invalid_repeating_section_title_placeholders.json, tests/schemas/invalid/test_invalid_string_transforms.json, tests/schemas/invalid/test_invalid_when_condition_list_property.json, tests/schemas/invalid/test_invalid_when_condition_property.json, tests/schemas/valid/test_list_collector_driving_question.json, tests/schemas/valid/test_list_summary_on_question.json, tests/schemas/valid/test_repeating_section.json, tests/schemas/valid/test_when_condition_property.json, tests/test_schema_validation.py
Added validation to check for the use of dumb quotes within lines of text. We should only be using smart quotes within our schema text. See http://smartquotesforsmartpeople.com/
Check the new tests created that find dumb quotes.
Run the validation tests against the new test schema.
=> Add quote validation

.github/workflows/build-for-staging.yml
=> add build for staging

.github/workflows/build-for-staging.yml
=> fixed script

.github/workflows/build-for-staging.yml
=> updated job title

.github/workflows/build-for-release.yml
=> EAR-1230 added release build script
