ONSdigital/eq-schema-validator

schemas/answers/definitions.json

The calculated reference was pointing to itself. Now it isn't 👍

Fixed calculated circular reference

---

schemas/blocks/interstitial.json
schemas/blocks/introduction.json
schemas/common_definitions.json
schemas/questions/date_range.json
schemas/questions/general.json
schemas/questions/relationship.json
schemas/questions/repeating_answer.json

Generalised `guidance_content` to `content` and allowed use in context with Interstitials

eQ 1450 Adding content to interstitial block

---

schemas/common_definitions.json

Routing based on numbers requires this.

Allow integers for when comparisons

---

schemas/questionnaire_v1.json

Adds view_submitted_responses attribute to main questionnaire.
**enabled** is a boolean to allow viewing of submitted responses for a questionnaire.
**timeout** is an integer of the number of seconds the link for submitted answers is available after submission.

Add view_submitted_responses to Questionnaire

---

schemas/questionnaire_v1.json

Within **view_submitted_response** object the required fields should read **duration** rather than **timeout**.  Part of #15

timeout renamed duration

---

schemas/answers/dropdown.json
schemas/common_definitions.json
schemas/questions/general.json

The drop-down input type requires a new schema validator to ensure that the schemas are accurate.
Card: https://trello.com/c/lZqYhhjw/1328-add-dropdown-input-type-m
1. In eq-survey-runner, checkout to branch: `eq-1328-add-dropdown-input-type`
2. Run the following:
`./scripts/test_schemas.sh data/en/`
Check that all the schemas pass

New validator for dropdown input type

---

.pylintrc
Pipfile
Pipfile.lock

We use pylint-mccabe to do complexity checking on our Python code. Recently this has become incompatible with the latest version of astroid (used by pylint) - infoxchange/pylint-mccabe#3. It also hasn't been updated in over 5 years.
We should replace it with the pylint built in complexity checker - https://pylint.readthedocs.io/en/latest/technical_reference/extensions.html#design-checker (as mentioned in PyCQA/astroid#471)
Does the linting work?

Replace pylint-mccabe with pylint built-in complexity checker

---

schemas/common_definitions.json

Addition of `date_comparison` to common `when` routing definition.

date_comparison routing definition

---

app/validation/validator.py
schemas/answers/definitions.json

Enforces that any answer type that uses options, ie Radios, Checkboxes, Dropdowns etc must contain at least 2 options. Also checks for duplicate option label and value between the options.
1. Ensure schema validation fails when an answer type that uses options doesn't have at least 2 options and vice versa.
2. Ensure that validation fails when options contain duplicates and vice versa.

Improve validation of answer options

---

schemas/answers/checkbox.json
schemas/answers/definitions.json
schemas/answers/dropdown.json
schemas/answers/radio.json

A recent change to the schema validator broke some Questionnaires (including LFS) that are being authored in Pre-prod.
The schema validator previously enforced that any multiple choice answers (i.e. Checkbox/Radio answers, must have a minimum of 2 options.
This PR changes the schema definitions of checkbox and radio to ensure that Radio answers must have a minimum of 2 options, but allow Checkbox answers to have a minimum of 1 Option (for single option checkbox answers).
This change should allow single option checkboxes and enforce a minimum of 2 options for radio answers. All other validations (e.g. failure if missing any options) should still apply.

Fixes validation for minimum number of checkbox/radio options.

---

app/validation/validator.py
schemas/answers/currency.json
schemas/answers/number.json
schemas/answers/percentage.json
schemas/answers/unit.json
tests/schemas/test_invalid_numeric_answers.json
tests/test_schema_validation.py

The "default" value will be stored in the answer store on POST when no value is given for the answer.

Add default for numeric answers

---

schemas/questions/date_range.json

Added `MonthYearDate` as one of the answer types for `DateRange` question type.
Needed to support changes in runner to support `MonthYearDate` ranges.
[Branch](https://github.com/ONSdigital/eq-survey-runner/tree/eq-1931-pipe-difference-between-two-dates)

Added support for month year date range

---

app/views/validate.py

Returning a `400` error makes it easier to detect if a schema is invalid

Don't return 200 status_code on error

---

ci/concourse.yml
ci/install.sh

Concourse is failing since latest update to pip.
I have pinned the version of `pip` and `pipenv` until this issue is resolved.
Note: Concourse is still throwing the same error as before but is able to carry on.
[Issue](https://github.com/wemake-services/wemake-django-template/issues/287)
I have also separated the scripts that are run in `concourse.yml` to `install.sh` so that it could be modified without resetting the `concourse.yml` each time.

Pin pip and pipenv to working versions in concourse

---

Pipfile
Pipfile.lock
app/validation/validator.py
schemas/answers/date.json
schemas/common_definitions.json
schemas/questions/date_range.json
tests/schemas/test_invalid_date_range_period.json
tests/schemas/test_invalid_single_date_min_max_period.json
tests/test_schema_validation.py

Added object types `minimum/maximum` to: 
- `DateRange` question for period validation
- `Date` answer type. 
Also added further validation in answer types where there is a minimum and a maximum so that, schema shouldn't fail. Only validates where there is a minimum and a maximum and both have `value` offset dates.

Eq 1947 date range validation

---

Pipfile
Pipfile.lock

Previous under dev dependencies, eq-compose wasn't picking it up and resulted in smoke test failures.
To Test:
Point schema-validator module in compose to this branch and run compose followed by smoke test. All should pass

Moved dateutil from dev dependency to project dependecies

---

app/validation/validator.py
schemas/answers/date.json
schemas/answers/month_year_date.json
schemas/common_definitions.json
tests/schemas/test_invalid_mm_yyyy_date_range_period.json
tests/test_schema_validation.py

Allow date validation to be added to MM-YYYY date ranges. 
Days can not then be used to define offsets or period limits.

Add date validation to MM-YYYY

---

.gitignore
app/validation/validator.py
schemas/questionnaire_v1.json
tests/schemas/test_invalid_date_range_period.json
tests/schemas/test_invalid_id_in_grouped_answers_to_calculate.json
tests/schemas/test_invalid_metadata.json
tests/schemas/test_invalid_mm_yyyy_date_range_period.json
tests/schemas/test_invalid_numeric_answers.json
tests/schemas/test_invalid_routing_block.json
tests/schemas/test_invalid_routing_group.json
tests/schemas/test_invalid_single_date_min_max_period.json
tests/schemas/test_numeric_default_with_routing.json
tests/schemas/test_schema_id_regex.json
tests/test_schema_validation.py

Runner [PR](https://github.com/ONSdigital/eq-survey-runner/pull/1571) must be merged first. Refer to runner PR for more context.
This PR enforces that:
1. `metadata` is present in the schema.
2. the mandatory metadata is present in all schemas: `user_id`, `period_id`
2. metadata used within the schema for piping are defined in the `metadata` field.
1. Ensure all schemas pass against the runner branch.
2. Edit a schema to ensure that if you do not define the piped metadata as required then it fails.
Ways of piping metadata:
1. `metadata.ru_name`
2. `metadata['ru_name']`
3. `"meta": "ru_name"`
> Update: Made metadata optional so that this can be merged without affecting (master) runner. The publisher [PR](https://github.com/ONSdigital/eq-publisher/pull/64) can also go in. A new validator PR …

Specify required metadata in schema

---

app/validation/validator.py
schemas/questionnaire_v1.json
tests/test_schema_validation.py

Runner [PR](https://github.com/ONSdigital/eq-survey-runner/pull/1571) must be merged first. Refer to runner PR for more context.
This PR enforces that:
1. `metadata` is present in the schema.
2. the mandatory metadata is present in all schemas: `user_id`, `period_id`
2. metadata used within the schema for piping are defined in the `metadata` field.
1. Ensure all schemas pass against the runner branch.
2. Edit a schema to ensure that if you do not define the piped metadata as required then it fails and vice versa.
Ways of piping metadata:
1. `metadata.ru_name`
2. `metadata['ru_name']`
3. `"meta": "ru_name"`

Enforce metadata in schemas

---

.gitignore
app/validation/validator.py
schemas/common_definitions.json
schemas/questions/calculated.json
schemas/questions/date_range.json
schemas/questions/general.json
schemas/questions/relationship.json
schemas/questions/repeating_answer.json
tests/schemas/test_invalid_multiple_question_titles.json
tests/schemas/test_invalid_routing_block.json
tests/test_schema_validation.py

We have defined a question `titles` object that allows for different versions of a question title depending on a given answer in a previous question. We also have defined the conditional(s) in the titles object to be exactly how when rules work. 
A question can now have a `title` string or `titles` object. Each `titles` object must have a default value, which is always the last value present, this cannot have any conditional with it as its the default value.
We have also added tests so that any answer id's in `when` conditions are valid answer id's.
Run SR branch https://github.com/ONSdigital/eq-survey-runner/tree/eq-1990-different-versions-of-question-titles against this branch, it should pass, and then try and break it based on our rules

Eq 1990 different versions of question titles

---

app/validation/validator.py
tests/schemas/test_invalid_date_range_period.json
tests/schemas/test_invalid_id_in_grouped_answers_to_calculate.json
tests/schemas/test_invalid_metadata.json
tests/schemas/test_invalid_mm_yyyy_date_range_period.json
tests/schemas/test_invalid_multiple_question_titles.json
tests/schemas/test_invalid_numeric_answers.json
tests/schemas/test_invalid_routing_block.json
tests/schemas/test_invalid_routing_group.json
tests/schemas/test_invalid_single_date_min_max_period.json
tests/schemas/test_numeric_default_with_routing.json
tests/schemas/test_schema_id_regex.json
tests/test_schema_validation.py

The introduction page expects RU Name to be present for default and northernireland themes.
This PR ensures ru_name is specified as required metadata in the schemas.

RU Name mandatory in metadata for Default/NI Themes

---

app/validation/validator.py
tests/schemas/test_invalid_routing_block.json
tests/test_schema_validation.py

Armed forces household census was throwing 500s, it had a when dependency on an id that does not exist , this was being missed by validator.
The root cause was that the id in the when was only being checked if an answer type was options. 
Code changed so as to validate that the independent variable is a known answer.
To Test:
Test schema changed to have invalid id for a non options answer type, so just run tests.

validating id in when of routing rules is a valid answer

---

app/validation/validator.py

Uses [best match](https://python-jsonschema.readthedocs.io/en/v2.6.0/errors/#best-match-and-relevance) from the python jsonschema library to return a best guess reason in addition to the erroneous block.

Return a "best match" reason for errors

---

schemas/answers/duration.json
schemas/common_definitions.json
schemas/questions/general.json
schemas/questions/repeating_answer.json

Add a Duration type.  Uses a field named `units` to define what the duration is made up of, currently only years/months are supported.

Add a Duration answer type

---

app/validation/validator.py
schemas/common_definitions.json
tests/schemas/test_invalid_routing_when_answer_count.json
tests/test_schema_validation.py

This PR adds syntax validation for routing_rules which make use of the number of answers to a repeated question.
This PR:
1. Adds JSON schema defintions
2. Adds sanity checking which cannot be easily caught by the schema validation
3. Adds a test to ensure incorrect inputs are found

Add validation for `answer_count` in when clauses

---

api.py
app/validation/validator.py
schemas/common_definitions.json
schemas/questionnaire_v1.json
tests/schemas/test_invalid_routing_block.json
tests/schemas/test_invalid_routing_group.json
tests/test_schema_validation.py

Under `routing_rules` in `repeat` we want to support a new type of `until` that will repeat until a condition is met (specified with a `when` clause).  The when clause only supports a subset of the behaviours it does elsewhere, only one is allowed in the list and only on `id`.

Add a repeating type of 'until'

---

schemas/questionnaire_v1.json

The `validator` attribute wasn't marked as required but is required in Runner

Validator required on metadata

---

app/validation/validator.py
schemas/questionnaire_v1.json
tests/schemas/test_invalid_calculated_summary.json
tests/schemas/test_invalid_date_range_period.json
tests/schemas/test_invalid_id_in_grouped_answers_to_calculate.json
tests/schemas/test_invalid_metadata.json
tests/schemas/test_invalid_mm_yyyy_date_range_period.json
tests/schemas/test_invalid_multiple_question_titles.json
tests/schemas/test_invalid_numeric_answers.json
tests/schemas/test_invalid_routing_block.json
tests/schemas/test_invalid_routing_group.json
tests/schemas/test_invalid_routing_when_answer_count.json
tests/schemas/test_invalid_single_date_min_max_period.json
tests/schemas/test_invalid_survey_id_whitespace.json
tests/schemas/test_invalid_yyyy_date_range_period.json
tests/schemas/test_numeric_default_with_routing.json
tests/schemas/test_schema_id_regex.json
tests/test_schema_validation.py

Changes the allowed structure of metadata to 
```
"metadata": [
{
"name": "period_id",
"validator": "string"
},
```
from
```
"metadata": {
"period_id": {
"validator": "string"
},
```
Json reformat is a pain, do we have any suggestions for a consistent formatter for JSON that we can automate?

Refactor metadata structure

---

schemas/questionnaire_v1.json
tests/schemas/test_invalid_metadata.json

In aid of flattening out `variant_flags` in to the top level claims object of the JWT, it became apparent that a boolean validator type was needed.
Tested against the updated schemas in https://github.com/ONSdigital/eq-survey-runner/pull/1715

Add boolean metadata value type, remove object

---

Pipfile
Pipfile.lock
README.md

The primary purpose of this was to update flask to a version that doesn't have a vulnerability in it.  The dev packages were unpinned because
- running pipenv update caused the following error `Could not find a version that matches astroid<2.0,>=1.6,>=2.0.0`
- dev packages shouldn't be pinned unless there is a good reason, which there didn't seem to be.
This has been tested, but only with the newly added instructions in the README.md file.

Unpin test packages, update dependencies

---

app/validation/validator.py
schemas/common_definitions.json
schemas/lists/currencies.json
tests/schemas/test_invalid_answer_comparison_id.json
tests/schemas/test_invalid_answer_comparison_types.json
tests/test_schema_validation.py

Runner is adding a `comparison_id` to the when clause.
This PR updates the json schema to allow for `comparison_id`.
- Since these when conditions can also be used in skip conditions, I have added validation for those too.
- Adding skip condition validation raised an issue with MWS survey in runner.
- Disallow `set` and `unset` with comparison_id
- Disallow comparison_id being used in `when` clauses in titles (since this could cause other issues and isn't needed by a customer)

Changes for comparison_id in when clauses

---

schemas/blocks/confirmation_question.json

In a repeat until pattern the `Do you need to add any thinf else` type question should be a ConfirmationQuestion as it is not needed on a summary page. This type of question however does not have routing rules and so validator should not enforce this.

Remove RoutingRules from required in ConfirmationQuestion

---

app/validation/validator.py
tests/schemas/test_valid_metadata.json
tests/test_schema_validation.py

Fixes #87 
This change ensures that metadata defined in the schema does not cause a validation error if it is not used within that schema. A change to the logic in this validation is required in order to support a new feature within author to add and remove metadata for a questionnaire.
The reverse logic should still work as expected. i.e. metadata that is being used without first being defined should still cause an error during validation.
Changes should look sensible.
All tests and code quality checks should pass.

Allow metadata to be defined but not used

---

schemas/questionnaire_v1.json

The lms schema has optional metadata fields for address playback (address_line1, address_line2, etc), which means we need to be able to have extra fields which are optional.
- Test with [this branch in survey-runner](https://github.com/ONSdigital/eq-survey-runner/pull/1804)
- Also running off [the go launcher pr](https://github.com/ONSdigital/go-launch-a-survey/pull/118)

Make optional fields in metadata possible

---

schemas/questionnaire_v1.json

Reverting a previous change, to add an 'optional_string'
- [Related PR for address playback](https://github.com/ONSdigital/eq-survey-runner/pull/1804)
- [Previous schema-validator PR for optional](https://github.com/ONSdigital/eq-schema-validator/pull/92)

Add 'optional_string' and remove 'optional' type

---

app/validation/validator.py
schemas/answers/currency.json
schemas/answers/definitions.json
schemas/answers/number.json
schemas/answers/percentage.json
schemas/answers/text_field.json
schemas/answers/unit.json
schemas/questions/mutually_exclusive.json
tests/schemas/test_invalid_multiple_question_titles.json
tests/schemas/test_invalid_mutually_exclusive_conditions.json
tests/schemas/test_invalid_numeric_answers.json
tests/schemas/test_invalid_survey_id_whitespace.json
tests/schemas/test_numeric_default_with_routing.json
tests/test_schema_validation.py

Add detail_answer to options as part of [Runner PR](https://github.com/ONSdigital/eq-survey-runner/pull/1920)
Initially only supports TextField.
Removes references to Child/Parent answer ids
Number of Mutually Exclusive answers can now be checked in schema json

Add detail_answer to Options

---

schemas/questionnaire_v1.json

Removes references to session prompts which have been removed from `eq-survey-runner` as per https://github.com/ONSdigital/eq-survey-runner/pull/1964
- Ensure tests pass

Remove references to session prompts

---

app/validation/validator.py
tests/schemas/test_invalid_option_value.json
tests/test_schema_validation.py

Validation to enforce that option values cannot contain piping.
I contemplated creating a whitelist of allowed characters but everything seems to accept string so I presume that would be restrictive. Instead I have done a very simple regex test that checks to see if anything looks like a piping value. However this might not be optimal. Suggestions welcome.
1. You can apply a piping value to an option label and publisher will send it as the value so I tested this against publisher using that but you have to change the publisher validator URL to `docker.for.mac.localhost:5001` once you have schema-validator running locally.
2. The unit tests should pass.

Ensure that answer option values do not contain piping

---

doc/decisions/0002-define-proxy-mechanism.md

The current implementation of proxy has limitations in terms of what it can be used for. This proposes new schema formats for interstitial and question to allow multiple variants per block.
I haven't made any changes to the JSON Schema, but will do so once this has been discussed and approved.

Change proxy implementation to be more flexible

---

schemas/answers/currency.json
schemas/answers/definitions.json
schemas/answers/number.json
schemas/answers/text_field.json
schemas/answers/unit.json
schemas/common_definitions.json

Required fields such as labels on options and some answer types only had to be a string - their contents was never validated. This meant that empty strings were viewed as being valid. This meant that runner could be made to look broken.
This is a breaking change for some of the test schemas in runner and here is the PR to resolve this https://github.com/ONSdigital/eq-survey-runner/pull/1984

Ensure that required fields are actually populated

---

schemas/string_interpolation/definitions.json
schemas/string_interpolation/transforms/concatenate_list.json
schemas/string_interpolation/transforms/format_currency.json
schemas/string_interpolation/transforms/format_date.json
schemas/string_interpolation/transforms/format_possessive.json
tests/schemas/test_string_transforms.json

Updates the arguments to placeholder transforms to be less generic and non conflicting with python globals. This allows transformations to meet our coding standards in runner.
Additionally add format_currency as a transform, as defined in the docs here: https://github.com/ONSdigital/eq-schema-validator/blob/v3/doc/decisions/0001-define-piping-in-a-structured-way.md#previous-answers-or-metadata-transformed-in-some-way
Once this is merged, https://github.com/ONSdigital/eq-survey-runner/pull/2010 will pass validation tests.

Use non global named args

---

app/validation/validator.py
tests/schemas/test_invalid_navigation.json
tests/test_schema_validation.py

This ensures that when navigation is visible that section title must be populated. Without this change when no section title is provided and navigation is visible this results in runner looking broken.

Validate that section title exists when navigation is enabled

---

README.md
app/validation/validator.py
schemas/blocks/list_collector.json
schemas/questionnaire_v1.json
tests/schemas/invalid/test_invalid_list_collector_non_radio.json
tests/schemas/invalid/test_invalid_list_collector_with_no_add_option.json
tests/schemas/invalid/test_invalid_list_collector_with_routing.json
tests/schemas/valid/test_list_collector.json
tests/test_schema_validation.py

Added a `ListCollector` Block type as defined in https://github.com/ONSdigital/eq-survey-runner/blob/v3/doc/architecture/decisions/0006-make-named-lists-a-first-class-construct.md

Add lists to schema validator

---

app/validation/validator.py
tests/schemas/invalid/test_invalid_placeholder_source_ids.json
tests/schemas/invalid/test_invalid_string_transforms.json
tests/schemas/valid/test_placeholder_source_ids.json
tests/schemas/valid/test_string_transforms.json
tests/test_schema_validation.py

**Motivation**
It's currently possible to insert invalid references to answer ids within placeholders, for example those that reference the same block or don't exist in the schema at all.
https://trello.com/c/s9gGN5wZ/2821-placeholder-answer-source-identifier-must-be-valid
**Changes**
Validate against invalid answer ids and update current schemas that use invalid answer ids.

Validate Placeholder Source Ids

---

app/validation/validator.py
schemas/common_definitions.json
tests/schemas/invalid/test_invalid_inconsistent_ids_in_variants.json
tests/test_schema_validation.py

To make the implementation of variants simpler in runner, this enforces that all question_ids are the same between each question_variant in a block. See https://github.com/ONSdigital/eq-survey-runner/pull/2021
I can't think of any situation where having multiple question_ids within a block is useful to us.

Enfore consistent ids across variants

---

schemas/string_interpolation/definitions.json
schemas/string_interpolation/transforms/calculate_years_difference.json
schemas/string_interpolation/transforms/format_date.json
tests/schemas/valid/test_string_transforms.json

format_date only allowed a date value to come from a source e.g. answers or metadata. This pull request extends the format_date transform to allow a fixed value.

Update format_date to work with fixed values

---

app/validation/validator.py
tests/schemas/valid/test_placeholder_source_ids.json

Using detail answers in routing and piping wasn't possible as the detail answers weren't being added to the list of answers generated before running validations. This pull request fixes the issue.

Include detail answers when validating answer references

---

app/validation/validator.py
tests/schemas/invalid/test_invalid_inconsistent_types_in_variants.json
tests/test_schema_validation.py

Add a schema validation step that checks question types and answer types within blocks are identical, including across variants.

Validate variants question type and answer type

---

app/validation/validator.py
schemas/answers/currency.json
schemas/answers/number.json
schemas/answers/percentage.json
schemas/answers/radio.json
schemas/answers/unit.json

Allows the use of defaults for 'Radio' answer types as on the census, if for proxy they want to treat unanswered the same as if the user answered 'Yes', so instead of duplication the rule 100+ times, this solves the problem if we are happy modifying the user's answer.
Have also fixed an issue with `_get_offset_date_value` which was causing validation errors where it was possible to compare a *string* object with a *datetime* object when one of min/max had an offset defined but the other did not.
A test did not seem necessary for these changes as one is fixing an *Exception* and the other is done by JSON schema.
Needed for: https://github.com/ONSdigital/eq-survey-runner/pull/2098

Allow default value for Radio answer and fix date comparision error

---

doc/decisions/0001-define-piping-in-a-structured-way.md
schemas/string_interpolation/transforms/format_date.json

The date format is interpreted in runner using Babel. Using a format of YYYY meant an ISO year-week calendar was used and so dates close to the start of the year could get formatted with the wrong year. Using yyyy fixes this.
See http://babel.pocoo.org/en/latest/dates.html#date-fields
and https://github.com/python-babel/babel/issues/419

Fix year in date format from YYYY to yyyy

---

app/validation/validator.py
schemas/questionnaire_v1.json
tests/schemas/invalid/test_invalid_hub_and_spoke_and_summary_confirmation_non_existent.json
tests/schemas/invalid/test_invalid_hub_and_spoke_with_summary_confirmation.json
tests/schemas/valid/test_hub_and_spoke.json
tests/test_schema_validation.py

Allows the use of a top-level object for the hub and spoke feature.
Needed for: https://github.com/ONSdigital/eq-survey-runner/pull/2142
For now, the hub is defined as a top-level schema object but this is subject to change once https://trello.com/c/BJPC98fW/3086-move-final-summary-block-out-of-sections is implemented. We should potentially have a single selection of the submission type for a schema ie Summary/Confirmation/Hub.
Test against runner branch.

Feature: Hub & Spoke

---

.gitignore
app/validation/validator.py
schemas/answers/relationship.json
schemas/blocks/relationship_collector.json
schemas/questionnaire_v1.json
schemas/questions/types/general.json
tests/schemas/invalid/test_invalid_relationship_list_doesnt_exist.json
tests/schemas/invalid/test_invalid_relationship_multiple_answers.json
tests/schemas/invalid/test_invalid_relationship_no_list_specified.json
tests/schemas/invalid/test_invalid_relationship_wrong_answer_type.json
tests/schemas/valid/test_relationship_collector.json
tests/test_schema_validation.py

There are two new definitions:
1) `/schemas/blocks/relationships_collector.json` uses a new enum, `RelationshipsCollector`, and uses a new mandatory `list` property. This is the id of the list that contains the list items for which relationships need to be collected.
2) `/schemas/answers/relationships.json` defines new answer options properties `relationships_title` sand `relationships_playback` that are unique to and mandatory for relationships answers.

Adds definitions for relationship collector

---

app/validation/validator.py
schemas/blocks/list_collector.json
schemas/blocks/primary_person_list_collector.json
tests/schemas/invalid/test_invalid_list_collector_bad_answer_reference_ids.json
tests/schemas/invalid/test_invalid_list_collector_bad_sub_block_types.json
tests/schemas/invalid/test_invalid_list_collector_duplicate_ids_multiple_collectors.json
tests/schemas/invalid/test_invalid_list_collector_non_radio.json
tests/schemas/invalid/test_invalid_list_collector_with_different_add_block_answer_ids.json
tests/schemas/invalid/test_invalid_list_collector_with_different_answer_ids_in_add_and_edit.json
tests/schemas/invalid/test_invalid_list_collector_with_no_add_option.json
tests/schemas/invalid/test_invalid_list_collector_with_routing.json
tests/schemas/invalid/test_invalid_primary_person_list_collector_add_block.json
tests/schemas/invalid/test_invalid_primary_person_list_collector_bad_answer_id.json
tests/schemas/invalid/test_invalid_primary_person_list_collector_bad_answer_value.json
tests/schemas/invalid/test_invalid_primary_person_list_collector_different_answer_ids_multi_collectors.json
tests/schemas/invalid/test_invalid_primary_person_list_collector_no_radio.json
tests/schemas/invalid/test_invalid_primary_person_list_collector_routing.json
tests/schemas/invalid/test_invalid_relationship_multiple_answers.json
tests/schemas/invalid/test_invalid_relationship_no_list_specified.json
tests/schemas/invalid/test_invalid_relationship_wrong_answer_type.json
tests/schemas/valid/test_list_collector.json
tests/schemas/valid/test_primary_person_list_collector.json
tests/schemas/valid/test_relationship_collector.json

To align with RelationshipCollector schema, ListCollector and PrimaryPersonListCollector  now uses `for_list` instead of `populates_list`.
Ensure:
- No change in behaviour, everything works as expected.

Rename 'populates_list' to 'for_list'

---

app/validation/validator.py
tests/test_schema_validation.py

Runner uses the pattern of an optional question with a
ConfirmationQuestion and later questions using the piped
answer quite often, the change being reverted does not allow
this pattern. See for example `test_confirmation.json`.
Ideally, the routing path should be worked out in validator
to allow it to check whether the piped answer will only be
displayed if the question has been answered. 
Adding the routing path is a fairly substantial piece of work, so to get things moving, I am removing the check in this PR and raising a card to manage it properly.
New trello card: https://trello.com/c/Oditc3Ne/3181-calculate-the-routing-path-in-validator

Remove check for placeholders on non-mandatory answers

---

app/validation/validator.py
schemas/when_rule/compare_to_answer_store.json
schemas/when_rule/compare_to_location.json
schemas/when_rule/compare_to_multiple_values.json
schemas/when_rule/compare_to_value.json
schemas/when_rule/definitions.json
tests/schemas/invalid/test_invalid_answer_comparison_id.json
tests/schemas/invalid/test_invalid_answer_comparison_types.json
tests/schemas/invalid/test_invalid_when_comparison_list.json
tests/schemas/invalid/test_invalid_when_condition_property.json
tests/schemas/valid/test_when_location_comparison.json
tests/test_schema_validation.py

Runner needs to be capable of displaying question variants based on the primary person, which is only available in the relationship location.
Modify comparisons to be structured in objects coming from either a 'answers' or 'location' source.
"comparison": {
"source": "location",
"id": "from_list_item_id"
}
Additionally, I've modified RelationshipCollector validation to work with variants.

Add Location Comparisons to when rules

---

schemas/common_definitions.json

New functionality required in runner means we need to allow arrays of values to be passed into the when array in routing conditions, this Pr makes this change and allows it.

Updated validator to allow values array in when conditions

---

schemas/blocks/list_collector.json
schemas/blocks/primary_person_list_collector.json
tests/schemas/valid/test_list_collector.json

Adding new keys for summaries shown when a section contains list collectors. These are used when a ListCollector is shown on SectionSummary blocks.

Add ListCollector keys for SectionSummary

---

schemas/answers/definitions.json

One of many PR to come to add support for Who Lives Here.
This PR allows the use of placeholders in answer option descriptions.

Extend support for placeholders to option descriptions

---

app/validation/validator.py
tests/schemas/valid/test_duplicate_answer_id_for_list_collector_valid.json

Currently, variants are not considered when checking for duplicate ids for ListCollector child blocks.
This PR ensure they are also skipped.
This is needed for WLH https://github.com/ONSdigital/eq-survey-runner/pull/2308
Ensure:
1. Duplicate answers ids are allowed for question variants of list collector child blocks.

Allow duplicate answer_ids for list collector variants

---

schemas/blocks/definitions.json
schemas/common_definitions.json

Extends the support of placeholders for content blocks.
Already supported in runner.
Used by Census Household.
- Check if placeholders are allowed for the new additions in the PR and ensure runner displays then correctly.

Extend support for placeholders for contents

---

schemas/answers/relationship.json
schemas/string_interpolation/definitions.json
tests/schemas/invalid/test_invalid_relationship_list_doesnt_exist.json
tests/schemas/invalid/test_invalid_relationship_multiple_answers.json
tests/schemas/invalid/test_invalid_relationship_no_list_specified.json
tests/schemas/invalid/test_invalid_relationship_wrong_answer_type.json
tests/schemas/valid/test_relationship_collector.json
tests/test_schema_validation.py

Adds a new key to placeholder value_source objects - `list_item_selector`, which is a string object that can be either list_item_id or to_list_item_id.
Placeholder strings in relationship blocks must now be resolved via transforms, not in code.
This supports changes in runner for resolving possesive transformations via a schema.

Relationship name piping

---

schemas/answers/relationship.json
tests/schemas/valid/test_relationship_collector.json

Adds a description property to relationship options.
* [👍] eq-translations updated to support any new schema keys which need translation - `description` is an existing no-context key.

Add descriptions to relationship options

---

schemas/answers/definitions.json

This PR is to allow a details_answers field to be numeric
This PR [#2279](ONSdigital/eq-survey-runner/pull/2279) needs this change to allow adding the validation needed

Allow detail_answer to be numeric

---

schemas/blocks/list_collector.json
schemas/blocks/question.json
schemas/questions/types/calculated.json
schemas/questions/types/date_range.json
schemas/questions/types/general.json
schemas/questions/types/mutually_exclusive.json
tests/schemas/invalid/test_invalid_answer_action_redirect_to_list_add_question.json
tests/schemas/valid/test_answer_action_redirect_to_list_add_question.json
tests/schemas/valid/test_list_collector.json
tests/schemas/valid/test_question_variants.json

Adds an optional `hide_on_section_summary` to question blocks.
* [:+1: ] eq-translations updated to support any new schema keys which need translation (no new keys)

Add show_on_section_summary to question blocks

---

schemas/blocks/list_collector_driving_question.json

Due to https://github.com/ONSdigital/eq-schema-validator/pull/160 and https://github.com/ONSdigital/eq-schema-validator/pull/159 being in flight at the same time ListCollectorDrivingQuestion does not currently support the show_on_section_summary property.
It needs to be added to complete https://github.com/ONSdigital/eq-survey-runner/pull/2367

Add show on section summary to driving question

---

schemas/blocks/primary_person_list_collector.json
schemas/questions/types/general.json

Census Coverage Survey was failing schema validation because there were routing rules attached to the Primary Person List Collector question.
I have added routing rules to the Primary Person list collector schema.

Add routing rules to the primary person schema

---

schemas/blocks/list_collector.json
tests/schemas/invalid/test_invalid_list_collector_bad_answer_reference_ids.json
tests/schemas/invalid/test_invalid_list_collector_duplicate_ids_multiple_collectors.json
tests/schemas/invalid/test_invalid_list_collector_non_radio.json
tests/schemas/invalid/test_invalid_list_collector_with_different_add_block_answer_ids.json
tests/schemas/invalid/test_invalid_list_collector_with_different_answer_ids_in_add_and_edit.json
tests/schemas/invalid/test_invalid_list_collector_with_no_add_option.json
tests/schemas/invalid/test_invalid_list_collector_with_routing_in_sub_block.json
tests/schemas/invalid/test_invalid_relationship_multiple_answers.json
tests/schemas/invalid/test_invalid_relationship_wrong_answer_type.json
tests/schemas/invalid/test_invalid_repeating_section_list_name.json
tests/schemas/invalid/test_invalid_repeating_section_title_placeholders.json
tests/schemas/valid/test_list_collector.json
tests/schemas/valid/test_list_collector_with_routing_rule.json
tests/schemas/valid/test_relationship_collector.json
tests/schemas/valid/test_repeating_section.json
tests/schemas/valid/test_when_location_comparison.json

A lot of test schemas were missing list collector summaries but it was not breaking any tests. Summaries were added back in to test schemas and changed to mandatory blocks of ListCollector type in schema validator. It does detect missing summaries in list collectors now. [Trello card](https://trello.com/c/WVveCTV4/3223-adding-missing-list-collector-summaries-to-test-schemas-xs).
All schemas in the tests/schemas/ directory will be evaluated as part of the unit tests. Any errors in these schemas will cause a failure.
Use schema validator's unit test:
`pipenv run ./scripts/run_tests_unit.sh`

Add missing list collector summaries to test schemas

---

app/validation/validator.py
doc/decisions/0003-plural-forms-in-schema-text.md
schemas/questionnaire_v1.json
schemas/string_interpolation/definitions.json
schemas/string_interpolation/transforms/number_to_words.json
tests/schemas/invalid/test_invalid_placeholder_plurals.json
tests/schemas/valid/test_placeholder_plurals.json
tests/test_questionnaire_validation.py

See https://github.com/ONSdigital/eq-schema-validator/blob/propose-plural-forms-in-schema-text/doc/decisions/0003-plural-forms-in-schema-text.md for the proposal to add plural forms to the schema. 
This pull request also adds the required schema. 
The code to check for valid value sources has been factored out of the placeholders validation. It now searches the schema for all references to value sources and checks their validity against answer ids, metadata and lists.

Propose plural forms in schema text

---

schemas/answers/radio.json

This adds new boolean "voluntary" property to radio answer. It needs to be merged before changes described on [this Trello card](https://trello.com/c/Wu3oraFw/3424-voluntary-questions-m) can be implemented. It makes validator up to date with [this design systems](https://github.com/ONSdigital/design-system/pull/660) change.

Add voluntary property to radio answer

---

schemas/answers/number.json
schemas/answers/text_field.json
tests/schemas/valid/test_placeholder_source_ids.json

This adds new boolean "open" property to be used in some voluntary radio and checkbox answers. It needs to be merged before changes described on [this Trello card](https://trello.com/c/g3esxHDn/3433-visible-write-ins-m) can be implemented. [PR of the runner change](hhttps://github.com/ONSdigital/eq-questionnaire-runner/pull/25).

Add visible write-ins

---

schemas/blocks/summary.json

I have added the `ListCollectorSummary` type and `title` field to the Summary schema.
This change is required for the refactor of Summary page types in eq-questionnaire-runner.

Add the list collector summary type

---

doc/decisions/0004-extend-and-improve-routing-rules.md

There are some issues with the current structure of routing rules:
- They only support limited `AND` and `OR` logic - `OR` is only supported outside of a `when` block leading to duplicate routing targets 
- Logic can't be nested for more nuanced rules
- Dynamic values (answers, metadata, lists) are referenced inconsistently
This pull request proposes a new structure to solve these issues.

Propose routing rules improvements
